/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { MonadPageMinter__factory } from "./MonadPageMinter__factory";
