/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { MonadPageMinter } from "./MonadPageMinter";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export { MonadPageMinter__factory } from "./factories/MonadPageMinter__factory";
