/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MonadPageMinterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAccess"
      | "hasVoted"
      | "mintFee"
      | "mintPage"
      | "owner"
      | "registry"
      | "submitTrustVote"
      | "totalPagesMinted"
      | "totalProtocolRevenue"
      | "updateMintFee"
      | "updatePageConfig"
      | "voteStakeAmount"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PageMinted" | "PageUpdated" | "TrustVoted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "mintFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mintPage",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTrustVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPagesMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalProtocolRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateMintFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePageConfig",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "voteStakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintPage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitTrustVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPagesMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProtocolRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMintFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePageConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace PageMintedEvent {
  export type InputTuple = [
    targetContract: AddressLike,
    creator: AddressLike,
    gateToken: AddressLike,
    minTokenToUnlock: BigNumberish,
    ipfsHash: string
  ];
  export type OutputTuple = [
    targetContract: string,
    creator: string,
    gateToken: string,
    minTokenToUnlock: bigint,
    ipfsHash: string
  ];
  export interface OutputObject {
    targetContract: string;
    creator: string;
    gateToken: string;
    minTokenToUnlock: bigint;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PageUpdatedEvent {
  export type InputTuple = [
    targetContract: AddressLike,
    gateToken: AddressLike,
    minTokenToUnlock: BigNumberish,
    newIpfsHash: string
  ];
  export type OutputTuple = [
    targetContract: string,
    gateToken: string,
    minTokenToUnlock: bigint,
    newIpfsHash: string
  ];
  export interface OutputObject {
    targetContract: string;
    gateToken: string;
    minTokenToUnlock: bigint;
    newIpfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustVotedEvent {
  export type InputTuple = [
    targetContract: AddressLike,
    voter: AddressLike,
    currentVotes: BigNumberish,
    creatorPayout: BigNumberish
  ];
  export type OutputTuple = [
    targetContract: string,
    voter: string,
    currentVotes: bigint,
    creatorPayout: bigint
  ];
  export interface OutputObject {
    targetContract: string;
    voter: string;
    currentVotes: bigint;
    creatorPayout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MonadPageMinter extends BaseContract {
  connect(runner?: ContractRunner | null): MonadPageMinter;
  waitForDeployment(): Promise<this>;

  interface: MonadPageMinterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAccess: TypedContractMethod<
    [_viewer: AddressLike, _targetContract: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  mintFee: TypedContractMethod<[], [bigint], "view">;

  mintPage: TypedContractMethod<
    [
      _targetContract: AddressLike,
      _gateToken: AddressLike,
      _minTokenToUnlock: BigNumberish,
      _ipfsMetadataHash: string
    ],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        creator: string;
        targetContract: string;
        gateToken: string;
        minTokenToUnlock: bigint;
        totalTrustVotes: bigint;
        totalStakedValue: bigint;
        ipfsMetadataHash: string;
        mintedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;

  submitTrustVote: TypedContractMethod<
    [_targetContract: AddressLike],
    [void],
    "payable"
  >;

  totalPagesMinted: TypedContractMethod<[], [bigint], "view">;

  totalProtocolRevenue: TypedContractMethod<[], [bigint], "view">;

  updateMintFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePageConfig: TypedContractMethod<
    [
      _targetContract: AddressLike,
      _gateToken: AddressLike,
      _minTokenToUnlock: BigNumberish,
      _newIpfsHash: string
    ],
    [void],
    "nonpayable"
  >;

  voteStakeAmount: TypedContractMethod<[], [bigint], "view">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAccess"
  ): TypedContractMethod<
    [_viewer: AddressLike, _targetContract: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintPage"
  ): TypedContractMethod<
    [
      _targetContract: AddressLike,
      _gateToken: AddressLike,
      _minTokenToUnlock: BigNumberish,
      _ipfsMetadataHash: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean
      ] & {
        creator: string;
        targetContract: string;
        gateToken: string;
        minTokenToUnlock: bigint;
        totalTrustVotes: bigint;
        totalStakedValue: bigint;
        ipfsMetadataHash: string;
        mintedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitTrustVote"
  ): TypedContractMethod<[_targetContract: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "totalPagesMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalProtocolRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateMintFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePageConfig"
  ): TypedContractMethod<
    [
      _targetContract: AddressLike,
      _gateToken: AddressLike,
      _minTokenToUnlock: BigNumberish,
      _newIpfsHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteStakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "PageMinted"
  ): TypedContractEvent<
    PageMintedEvent.InputTuple,
    PageMintedEvent.OutputTuple,
    PageMintedEvent.OutputObject
  >;
  getEvent(
    key: "PageUpdated"
  ): TypedContractEvent<
    PageUpdatedEvent.InputTuple,
    PageUpdatedEvent.OutputTuple,
    PageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TrustVoted"
  ): TypedContractEvent<
    TrustVotedEvent.InputTuple,
    TrustVotedEvent.OutputTuple,
    TrustVotedEvent.OutputObject
  >;

  filters: {
    "PageMinted(address,address,address,uint256,string)": TypedContractEvent<
      PageMintedEvent.InputTuple,
      PageMintedEvent.OutputTuple,
      PageMintedEvent.OutputObject
    >;
    PageMinted: TypedContractEvent<
      PageMintedEvent.InputTuple,
      PageMintedEvent.OutputTuple,
      PageMintedEvent.OutputObject
    >;

    "PageUpdated(address,address,uint256,string)": TypedContractEvent<
      PageUpdatedEvent.InputTuple,
      PageUpdatedEvent.OutputTuple,
      PageUpdatedEvent.OutputObject
    >;
    PageUpdated: TypedContractEvent<
      PageUpdatedEvent.InputTuple,
      PageUpdatedEvent.OutputTuple,
      PageUpdatedEvent.OutputObject
    >;

    "TrustVoted(address,address,uint256,uint256)": TypedContractEvent<
      TrustVotedEvent.InputTuple,
      TrustVotedEvent.OutputTuple,
      TrustVotedEvent.OutputObject
    >;
    TrustVoted: TypedContractEvent<
      TrustVotedEvent.InputTuple,
      TrustVotedEvent.OutputTuple,
      TrustVotedEvent.OutputObject
    >;
  };
}
